### PR TITLE
Donor recognition page

### PR DESCRIPTION
**Pull request by DevinClark**
WIP

Slim layout came from #15.

Using middleman's data functionality to store the donors as json files.

- [x] Responsive
- [ ] Datas
- [ ] How to link to it

### CODE REVIEW

**Comment by DevinClark** [comment]
OH! Also need to figure out how we want to link to this on the website.

**Comment by DevinClark** [comment]
Fixed some responsive issues and added a logo to the slim layout.

@amandaharlin @the-simian Do we have data for the donors/organizers? Format doesn't really matter (I can transform to the below style).

```js
[{
   "name": "SST Software",
   "image_url": "sst.png",
   "level": "Gold"
}]
```

**Comment by amandaharlin** [comment]
bump ~ devin still wants some data (thank you for the reminder!)

**Comment by jagthedrummer** [comment]
I merged these changes to master, and then tweaked things a bit. I thought that GitHub would recognize that all of the commits in this PR are now in master and automatically show the PR as merged. Not sure... Anyway, thanks for the work on this @DevinClark!

**Pull request closed without merging**
